// src/main/webui/src/pages/Payloads.jsx
import { createMutation, createQuery, useQueryClient } from '@tanstack/solid-query';
import { safeFetch } from '../utils/safeFetch';
import { useNavigate } from '@solidjs/router';
import { Plus, Download, Edit, Trash } from 'lucide-solid';
import { Show, For, createEffect } from 'solid-js';
import { Title } from '@solidjs/meta';

export default function Payloads() {
    const queryClient = useQueryClient();
    const navigate = useNavigate();

    const payloadsQuery = createQuery(() => ({
        queryKey: ['payloads'],
        queryFn: () => safeFetch('/api/payloads').then(res => {
            if (!Array.isArray(res)) {
                throw new Error("API returned invalid data format");
            }
            return res;
        })
    }));

    const deleteMutation = createMutation(() => ({
        mutationFn: (id) => safeFetch(`/api/payloads/${id}`, { method: 'DELETE' }),
        onSuccess: () => {
            alert('Payload deleted successfully');
            queryClient.invalidateQueries({ queryKey: ['payloads'] });
        },
        onError: (err) => {
            alert('Failed to delete payload: ' + err.message);
        }
    }));

    const handleDelete = (id) => {
        if (window.confirm('Are you sure you want to delete this payload?')) {
            deleteMutation.mutate(id);
        }
    };

    const payloads = () => payloadsQuery.data || [];
    const isLoading = () => payloadsQuery.isPending;
    const hasError = () => payloadsQuery.error;
    const errorMessage = () => payloadsQuery.error?.message || String(payloadsQuery.error);

    return (
        <div class="space-y-6 w-full">
            <Title>Payloads | TestState</Title>
            {/* Header */}
            <div class="flex justify-between items-center">
                <h1 class="text-2xl font-bold">Payloads</h1>
                <button 
                    class="btn btn-primary btn-sm flex items-center gap-1.5" 
                    onClick={() => navigate('/payloads/new')}
                >
                    <Plus size={16} />
                    <span>New</span>
                </button>
            </div>

            {/* Content states */}
            <Show when={isLoading()}>
                <div class="flex flex-col items-center justify-center min-h-[30vh] gap-3">
                    <span class="loading loading-spinner loading-md text-primary"></span>
                    <p class="text-sm text-base-content/60">Loading payloads...</p>
                </div>
            </Show>

            <Show when={!isLoading() && hasError()}>
                <div class="alert alert-error">
                    <span>Error: {errorMessage()}</span>
                </div>
            </Show>

            <Show when={!isLoading() && !hasError()}>
                {/* Payloads Grid */}
                <Show when={payloads().length === 0}>
                    <div class="card bg-base-100 border border-base-200 shadow-sm p-8 text-center space-y-3">
                        <p class="text-base-content/60 text-sm">No payloads configured.</p>
                        <div class="flex justify-center">
                            <button class="btn btn-ghost btn-sm text-primary" onClick={() => navigate('/payloads/new')}>
                                Create New
                            </button>
                        </div>
                    </div>
                </Show>

                <Show when={payloads().length > 0}>
                    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                        <For each={payloads()}>
                            {(payload) => (
                                <div class="card bg-base-100 border border-base-200 shadow-sm hover:shadow-md transition-shadow flex flex-col justify-between">
                                    <div class="card-body p-5 gap-3 flex-grow">
                                        <div class="flex justify-between items-start gap-4">
                                            <h2 class="card-title text-base font-bold truncate" title={payload.name}>
                                                {payload.name}
                                            </h2>
                                            <span class="badge badge-warning badge-sm font-mono shrink-0">
                                                {payload.type}
                                            </span>
                                        </div>
                                        <Show when={payload.description}>
                                            <p class="text-xs text-base-content/60 line-clamp-3 flex-grow">
                                                {payload.description}
                                            </p>
                                        </Show>
                                    </div>
                                    <div class="px-5 pb-5">
                                        <div class="h-[1px] bg-base-200 mb-4" />
                                        <div class="flex justify-end items-center gap-2">
                                            <Show when={payload.attachmentName}>
                                                <a
                                                    href={`/api/payloads/${payload.id}/attachment`}
                                                    class="btn btn-xs btn-outline flex items-center gap-1"
                                                    title={`Export: ${payload.attachmentName}`}
                                                    download
                                                >
                                                    <Download size={12} />
                                                    <span>Export</span>
                                                </a>
                                            </Show>
                                            <button
                                                class="btn btn-xs btn-info flex items-center gap-1"
                                                onClick={() => navigate(`/payloads/${payload.id}/edit`)}
                                            >
                                                <Edit size={12} />
                                                <span>Edit</span>
                                            </button>
                                            <button
                                                class="btn btn-xs btn-error flex items-center gap-1"
                                                onClick={() => handleDelete(payload.id)}
                                                disabled={deleteMutation.isPending && deleteMutation.variables === payload.id}
                                            >
                                                <Show when={deleteMutation.isPending && deleteMutation.variables === payload.id}>
                                                    <span class="loading loading-spinner loading-xs"></span>
                                                </Show>
                                                <Show when={!(deleteMutation.isPending && deleteMutation.variables === payload.id)}>
                                                    <Trash size={12} />
                                                </Show>
                                                <span>Delete</span>
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            )}
                        </For>
                    </div>
                </Show>
            </Show>
        </div>
    );
}

// src/main/webui/src/pages/Payloads.vue
<script setup>
import { computed } from 'vue';
import { useQuery, useMutation, useQueryClient } from '@tanstack/vue-query';
import { safeFetch } from '@/utils/safeFetch';
import { useRouter } from 'vue-router';

const router = useRouter();
const queryClient = useQueryClient();

const { data: payloadsData, isPending: isLoading, error: hasError } = useQuery({
  queryKey: ['payloads'],
  queryFn: () => safeFetch('/api/payloads').then(res => {
    if (!Array.isArray(res)) {
      throw new Error("API returned invalid data format");
    }
    return res;
  })
});

const deleteMutation = useMutation({
  mutationFn: (id) => safeFetch(`/api/payloads/${id}`, { method: 'DELETE' }),
  onSuccess: () => {
    alert('Payload deleted successfully');
    queryClient.invalidateQueries({ queryKey: ['payloads'] });
  },
  onError: (err) => {
    alert('Failed to delete payload: ' + err.message);
  }
});

const handleDelete = (id) => {
  if (window.confirm('Are you sure you want to delete this payload?')) {
    deleteMutation.mutate(id);
  }
};

const handleExport = (id, filename) => {
  const a = document.createElement('a');
  a.href = `/api/payloads/${id}/attachment`;
  a.download = filename || 'attachment';
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
};

const payloads = computed(() => payloadsData.value || []);
const errorMessage = computed(() => hasError.value?.message || String(hasError.value));
</script>

<template>
  <div class="space-y-6 w-full">
    <!-- Header -->
    <div class="flex justify-between items-center">
      <h1 class="text-2xl font-bold tracking-tight">
        Payloads
      </h1>
      <UButton 
        label="New" 
        size="sm" 
        icon="i-lucide-plus"
        @click="router.push('/payloads/new')"
      />
    </div>

    <!-- Loading State -->
    <div
      v-if="isLoading"
      class="flex flex-col items-center justify-center min-h-[30vh] gap-3"
    >
      <UIcon name="i-lucide-loader-2" class="animate-spin w-10 h-10 text-primary-500" />
      <p class="text-sm text-gray-500">
        Loading payloads...
      </p>
    </div>

    <!-- Error State -->
    <UAlert
      v-else-if="hasError"
      title="Error loading payloads"
      :description="errorMessage"
      color="error"
      variant="solid"
      class="w-full"
    />

    <!-- Empty State -->
    <UCard
      v-else-if="payloads.length === 0"
      class="text-center py-8 shadow-sm"
    >
      <p class="text-gray-500 text-sm">
        No payloads configured.
      </p>
      <div class="flex justify-center mt-3">
        <UButton 
          label="Create New" 
          variant="link" 
          size="sm" 
          @click="router.push('/payloads/new')"
        />
      </div>
    </UCard>

    <!-- Grid View -->
    <div
      v-else
      class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6"
    >
      <UCard 
        v-for="payload in payloads" 
        :key="payload.id"
        class="hover:shadow-md transition-shadow flex flex-col justify-between"
        :ui="{ body: 'flex-grow flex flex-col justify-between p-5' }"
      >
        <div class="space-y-3 flex-grow">
          <div class="flex justify-between items-start gap-4">
            <h2
              class="text-base font-bold truncate text-gray-800 dark:text-gray-100"
              :title="payload.name"
            >
              {{ payload.name }}
            </h2>
            <UBadge 
              color="warning" 
              variant="subtle" 
              size="sm"
            >
              {{ payload.type }}
            </UBadge>
          </div>
          <p
            v-if="payload.description"
            class="text-xs text-gray-500 dark:text-gray-400 line-clamp-3"
          >
            {{ payload.description }}
          </p>
        </div>
        
        <USeparator class="my-4" />
        
        <div class="flex justify-end items-center gap-2">
          <UButton 
            v-if="payload.attachmentName"
            label="Export" 
            color="neutral"
            variant="outline"
            size="sm" 
            icon="i-lucide-download"
            @click="handleExport(payload.id, payload.attachmentName)"
          />
          <UButton 
            label="Edit" 
            color="neutral"
            variant="outline"
            size="sm" 
            icon="i-lucide-edit"
            @click="router.push(`/payloads/${payload.id}/edit`)"
          />
          <UButton 
            label="Delete" 
            color="error"
            variant="outline"
            size="sm" 
            icon="i-lucide-trash"
            :loading="deleteMutation.isPending.value && deleteMutation.variables.value === payload.id"
            @click="handleDelete(payload.id)"
          />
        </div>
      </UCard>
    </div>
  </div>
</template>
