// src/main/webui/src/pages/SavePayloadForm.vue
<script setup>
import { ref } from 'vue';
import { useMutation } from '@tanstack/vue-query';
import { safeFetch } from '@/utils/safeFetch';

const props = defineProps({
  sessionId: {
    type: String,
    required: true
  },
  item: {
    type: Object,
    required: true
  }
});

const emit = defineEmits(['save-success']);

const name = ref(`Translated: ${props.item.name || props.item.type}`);
const description = ref(`Translated ${props.item.type} from session ${props.sessionId}`);

const mutation = useMutation({
  mutationFn: (body) => safeFetch(`/api/translations/sessions/${props.sessionId}/payloads/${props.item.index}/save`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json'
    },
    body: JSON.stringify(body)
  }),
  onSuccess: () => {
    emit('save-success');
  },
  onError: (err) => {
    alert('Failed to save payload: ' + err.message);
  }
});

const handleSubmit = (e) => {
  e.preventDefault();
  const n = name.value;
  if (!n) return;
  mutation.mutate({
    name: n,
    description: description.value
  });
};
</script>

<template>
  <form
    class="mt-4 pt-4 border-t border-gray-200 dark:border-gray-800 space-y-3"
    @submit="handleSubmit"
  >
    <span class="text-xs text-gray-400 block font-semibold">Save as database payload:</span>
    <div class="flex flex-col gap-1.5 w-full">
      <UInput
        v-model="name"
        placeholder="Name"
        required
        class="w-full text-xs"
        size="sm"
      />
    </div>
    <div class="flex flex-col gap-1.5 w-full">
      <UInput
        v-model="description"
        placeholder="Description"
        class="w-full text-xs"
        size="sm"
      />
    </div>
    <div class="flex justify-end">
      <UButton
        type="submit"
        label="Save"
        size="xs"
        icon="i-lucide-save"
        :loading="mutation.isPending.value"
      />
    </div>
  </form>
</template>

// src/main/webui/src/pages/SavePayloadForm.svelte
<script>
  import { createMutation } from '@tanstack/svelte-query';
  import { safeFetch } from '@/utils/safeFetch';
  import Save from '@lucide/svelte/icons/save';
import Loader2 from '@lucide/svelte/icons/loader-2';

  let { sessionId, item, onSaveSuccess } = $props();

  let name = $state('');
  let description = $state('');

  $effect(() => {
    name = `Translated: ${item.name || item.type}`;
    description = `Translated ${item.type} from session ${sessionId}`;
  });

  const mutation = createMutation({
    mutationFn: (body) => safeFetch(`/api/translations/sessions/${sessionId}/payloads/${item.index}/save`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify(body)
    }),
    onSuccess: () => {
      if (onSaveSuccess) onSaveSuccess();
    },
    onError: (err) => {
      alert('Failed to save payload: ' + err.message);
    }
  });

  const handleSubmit = (e) => {
    e.preventDefault();
    if (!name) return;
    $mutation.mutate({
      name,
      description
    });
  };
</script>

<form class="mt-4 pt-4 border-t border-surface-200 dark:border-surface-800 space-y-3" onsubmit={handleSubmit}>
  <span class="text-xs text-surface-500 dark:text-surface-400 block font-semibold">Save as database payload:</span>
  <div class="w-full">
    <input
      type="text"
      bind:value={name}
      placeholder="Name"
      required
      class="input p-2 rounded-lg bg-surface-50 dark:bg-surface-950 border border-surface-300 dark:border-surface-850 w-full text-sm"
    />
  </div>
  <div class="w-full">
    <input
      type="text"
      bind:value={description}
      placeholder="Description"
      class="input p-2 rounded-lg bg-surface-50 dark:bg-surface-950 border border-surface-300 dark:border-surface-850 w-full text-sm"
    />
  </div>
  <div class="flex justify-end">
    <button
      type="submit"
      class="btn btn-sm preset-filled-primary-500 flex items-center gap-1"
      disabled={$mutation.isPending}
    >
      {#if $mutation.isPending}
        <Loader2 class="animate-spin" size={12} />
      {:else}
        <Save size={12} />
      {/if}
      Save
    </button>
  </div>
</form>
