// src/main/webui/src/pages/TestForm.jsx
import { createMutation, createQuery, useQueryClient } from '@tanstack/solid-query';
import { safeFetch } from '../utils/safeFetch';
import { useNavigate, useParams } from '@solidjs/router';
import { ArrowLeft, Copy, Save } from 'lucide-solid';
import { createSignal, createEffect, Show, For } from 'solid-js';
import { Title } from '@solidjs/meta';

function TestFormInner(props) {
    const navigate = useNavigate();
    const queryClient = useQueryClient();

    const [name, setName] = createSignal('');
    const [description, setDescription] = createSignal('');
    const [testType, setTestType] = createSignal('');
    const [payloadIds, setPayloadIds] = createSignal([]);
    const [errorMsg, setErrorMsg] = createSignal(null);

    const saveMutation = createMutation(() => ({
        mutationFn: (body) => {
            const url = props.isEdit ? `/api/tests/${props.id}` : '/api/tests';
            const method = props.isEdit ? 'PUT' : 'POST';
            return safeFetch(url, {
                method,
                headers: {
                    'Content-Type': 'application/json'
                },
                body: JSON.stringify(body)
            });
        },
        onSuccess: () => {
            queryClient.invalidateQueries({ queryKey: ['tests-data'] });
            navigate('/tests');
        },
        onError: (err) => {
            setErrorMsg(err.message);
        }
    }));

    const copyMutation = createMutation(() => ({
        mutationFn: () => safeFetch(`/api/tests/${props.id}/copy`, { method: 'POST' }),
        onSuccess: () => {
            queryClient.invalidateQueries({ queryKey: ['tests-data'] });
            navigate('/tests');
        },
        onError: (err) => {
            alert('Failed to duplicate test: ' + err.message);
        }
    }));

    createEffect(() => {
        const ent = props.entity;
        if (ent) {
            setName(ent.name || '');
            setDescription(ent.description || '');
            setTestType(ent.testType || '');
            setPayloadIds(ent.payloads?.map(p => p.id) || []);
        } else if (props.availableTypes?.length > 0 && !testType()) {
            setTestType(props.availableTypes[0]);
        }
    });

    const getPayloadRequirement = (payloadType) => {
        const tType = testType();
        const ags = props.agents;
        if (!tType || !ags) return null;
        const requirements = new Map(); // type -> 'REQUIRED' | 'RECOMMENDED'
        ags.forEach(agent => {
            const test = agent.supportedTests?.find(t => t.testType === tType);
            if (test) {
                test.requiredPayloadTypes?.forEach(r => requirements.set(r, 'REQUIRED'));
                test.optionalPayloadTypes?.forEach(o => {
                    if (requirements.get(o) !== 'REQUIRED') {
                        requirements.set(o, 'RECOMMENDED');
                    }
                });
            }
        });
        return requirements.get(payloadType) || null;
    };

    const handleSubmit = (e) => {
        e.preventDefault();
        setErrorMsg(null);

        if (!name()) {
            setErrorMsg("Name is required");
            return;
        }
        if (!testType()) {
            setErrorMsg("Type is required");
            return;
        }

        saveMutation.mutate({
            name: name(),
            description: description(),
            testType: testType(),
            payloadIds: payloadIds()
        });
    };

    const handleCheck = (payloadId, checked) => {
        if (checked) {
            setPayloadIds(prev => [...prev, payloadId]);
        } else {
            setPayloadIds(prev => prev.filter(val => val !== payloadId));
        }
    };

    return (
        <div class="space-y-6 w-full">
            {/* Header */}
            <div class="flex justify-between items-center">
                <h1 class="text-2xl font-bold">{props.isEdit ? 'Edit Test' : 'New Test'}</h1>
                <div class="flex gap-2">
                    <Show when={props.isEdit}>
                        <button
                            class="btn btn-outline btn-sm flex items-center gap-1.5"
                            onClick={() => copyMutation.mutate()}
                            disabled={copyMutation.isPending}
                        >
                            <Show when={copyMutation.isPending}>
                                <span class="loading loading-spinner loading-xs"></span>
                            </Show>
                            <Show when={!copyMutation.isPending}>
                                <Copy size={16} />
                            </Show>
                            <span>Copy</span>
                        </button>
                    </Show>
                    <button 
                        class="btn btn-outline btn-sm flex items-center gap-1.5"
                        onClick={() => navigate('/tests')}
                    >
                        <ArrowLeft size={16} />
                        <span>Return</span>
                    </button>
                </div>
            </div>

            <Show when={errorMsg()}>
                <div class="alert alert-error flex justify-between items-center">
                    <span>{errorMsg()}</span>
                    <button class="btn btn-ghost btn-xs text-error-content" onClick={() => setErrorMsg(null)}>✕</button>
                </div>
            </Show>

            <form onSubmit={handleSubmit} class="space-y-6">
                {/* Settings Card */}
                <div class="card bg-base-100 border border-base-200 shadow-sm">
                    <div class="card-body p-5 space-y-4">
                        <h2 class="card-title text-base font-semibold border-b border-base-200 pb-2">Settings</h2>

                        <div class="form-control w-full">
                            <label class="label">
                                <span class="label-text font-semibold">Name <span class="text-error">*</span></span>
                            </label>
                            <input
                                type="text"
                                placeholder="Enter test name"
                                required
                                class="input input-bordered w-full"
                                value={name()}
                                onInput={(e) => setName(e.currentTarget.value)}
                            />
                        </div>

                        <div class="form-control w-full">
                            <label class="label">
                                <span class="label-text font-semibold">Description</span>
                            </label>
                            <textarea
                                placeholder="Enter description"
                                rows="3"
                                class="textarea textarea-bordered w-full"
                                value={description()}
                                onInput={(e) => setDescription(e.currentTarget.value)}
                            />
                        </div>

                        <div class="form-control w-full">
                            <label class="label">
                                <span class="label-text font-semibold">Type <span class="text-error">*</span></span>
                            </label>
                            <input
                                type="text"
                                placeholder="Select or enter test type"
                                required
                                class="input input-bordered w-full"
                                list="available-test-types"
                                value={testType()}
                                onInput={(e) => setTestType(e.currentTarget.value)}
                            />
                            <datalist id="available-test-types">
                                <For each={props.availableTypes}>
                                    {(item) => <option value={item} />}
                                </For>
                            </datalist>
                        </div>
                    </div>
                </div>

                {/* Payloads Card */}
                <div class="card bg-base-100 border border-base-200 shadow-sm">
                    <div class="card-body p-5 space-y-4">
                        <h2 class="card-title text-base font-semibold border-b border-base-200 pb-2">Payloads</h2>

                        <div class="space-y-2 max-h-[300px] overflow-y-auto pr-1">
                            <Show when={props.allPayloads.length === 0}>
                                <div class="text-center py-6 text-sm text-base-content/50">
                                    <span>Empty. </span>
                                    <button class="link link-primary" type="button" onClick={() => navigate('/payloads/new')}>New.</button>
                                </div>
                            </Show>
                            <Show when={props.allPayloads.length > 0}>
                                <div class="space-y-2">
                                    <For each={props.allPayloads}>
                                        {(payload) => {
                                            const reqState = () => getPayloadRequirement(payload.type);
                                            const isChecked = () => payloadIds().includes(payload.id);
                                            return (
                                                <div 
                                                    class={`flex items-center justify-between p-3 rounded-lg border border-base-200 transition-colors ${
                                                        isChecked() ? 'bg-primary/5 border-primary/20' : 'bg-base-300/40'
                                                    }`}
                                                >
                                                    <label class="label cursor-pointer flex justify-start items-center gap-3 w-full">
                                                        <input 
                                                            type="checkbox" 
                                                            class="checkbox checkbox-primary checkbox-sm"
                                                            checked={isChecked()}
                                                            onChange={(e) => handleCheck(payload.id, e.currentTarget.checked)}
                                                        />
                                                        <div class="flex flex-col">
                                                            <span class="font-semibold text-sm">{payload.name}</span>
                                                            <span class="font-mono text-xs text-base-content/50">{payload.type}</span>
                                                        </div>
                                                    </label>
                                                    <Show when={reqState()}>
                                                        <span class={`badge badge-sm shrink-0 font-bold ${
                                                            reqState() === 'REQUIRED' ? 'badge-error text-error-content' : 'badge-success text-success-content'
                                                        }`}>
                                                            {reqState()}
                                                        </span>
                                                    </Show>
                                                </div>
                                            );
                                        }}
                                    </For>
                                </div>
                            </Show>
                        </div>
                    </div>
                </div>

                <button
                    type="submit"
                    class="btn btn-primary w-full flex items-center gap-2"
                    disabled={saveMutation.isPending}
                >
                    <Show when={saveMutation.isPending}>
                        <span class="loading loading-spinner loading-sm"></span>
                    </Show>
                    <Show when={!saveMutation.isPending}>
                        <Save size={18} />
                    </Show>
                    <span>Save</span>
                </button>
            </form>
        </div>
    );
}

export default function TestForm() {
    const params = useParams();
    const isEdit = () => !!params.id;

    const formContextQuery = createQuery(() => ({
        queryKey: ['test-form-context', params.id],
        queryFn: async () => {
            const [types, payloads, entity, agents] = await Promise.all([
                safeFetch('/api/tests/available-types'),
                safeFetch('/api/payloads'),
                isEdit() ? safeFetch(`/api/tests/${params.id}`) : Promise.resolve(null),
                safeFetch('/api/agents')
            ]);
            return { types, payloads, entity, agents };
        }
    }));

    const isLoading = () => formContextQuery.isPending;
    const hasError = () => formContextQuery.error;
    const errorMessage = () => formContextQuery.error?.message || String(formContextQuery.error);

    return (
        <div class="max-w-3xl mx-auto w-full">
            <Title>{isEdit() ? 'Edit' : 'Create'} Test | TestState</Title>
            <Show when={isLoading()}>
                <div class="flex flex-col items-center justify-center min-h-[30vh] gap-3">
                    <span class="loading loading-spinner loading-md text-primary"></span>
                    <p class="text-sm text-base-content/60">Loading Form data...</p>
                </div>
            </Show>

            <Show when={hasError()}>
                <div class="alert alert-error">
                    <span>Error: {errorMessage()}</span>
                </div>
            </Show>

            <Show when={!isLoading() && !hasError()}>
                <TestFormInner
                    isEdit={isEdit()}
                    id={params.id}
                    availableTypes={formContextQuery.data.types}
                    allPayloads={formContextQuery.data.payloads}
                    entity={formContextQuery.data.entity}
                    agents={formContextQuery.data.agents}
                />
            </Show>
        </div>
    );
}

// src/main/webui/src/pages/TestForm.svelte
<script>
  import { createQuery, createMutation, useQueryClient } from '@tanstack/svelte-query';
  import { safeFetch } from '@/utils/safeFetch';
  import { navigate, route } from '@/router.js';
  import Copy from '@lucide/svelte/icons/copy';
import ArrowLeft from '@lucide/svelte/icons/arrow-left';
import Save from '@lucide/svelte/icons/save';
import Loader2 from '@lucide/svelte/icons/loader-2';

  let id = $derived(route.params.id);

  const queryClient = useQueryClient();
  const isEdit = $derived(!!id);

  let name = $state('');
  let description = $state('');
  let testType = $state('');
  let payloadIds = $state([]);
  let errorMsg = $state(null);

  const contextQuery = createQuery({
    get queryKey() { return ['test-form-context', id]; },
    get queryFn() {
      return async () => {
        const [types, payloads, entity, agents] = await Promise.all([
          safeFetch('/api/tests/available-types'),
          safeFetch('/api/payloads'),
          isEdit ? safeFetch(`/api/tests/${id}`) : Promise.resolve(null),
          safeFetch('/api/agents')
        ]);
        return { types, payloads, entity, agents };
      };
    }
  });

  let availableTypes = $derived($contextQuery.data?.types || []);
  let allPayloads = $derived($contextQuery.data?.payloads || []);
  let entity = $derived($contextQuery.data?.entity);
  let agents = $derived($contextQuery.data?.agents || []);

  $effect(() => {
    if (entity) {
      name = entity.name || '';
      description = entity.description || '';
      testType = entity.testType || '';
      payloadIds = entity.payloads?.map(p => p.id) || [];
    }
  });

  const saveMutation = createMutation({
    mutationFn: (body) => {
      const url = isEdit ? `/api/tests/${id}` : '/api/tests';
      const method = isEdit ? 'PUT' : 'POST';
      return safeFetch(url, {
        method,
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify(body)
      });
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['tests'] });
      navigate('/tests');
    },
    onError: (err) => {
      errorMsg = err.message;
    }
  });

  const copyMutation = createMutation({
    mutationFn: () => safeFetch(`/api/tests/${id}/copy`, { method: 'POST' }),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['tests'] });
      navigate('/tests');
    },
    onError: (err) => {
      alert('Failed to duplicate test: ' + err.message);
    }
  });

  const getPayloadRequirement = (payloadType) => {
    const tType = testType;
    const ags = agents;
    if (!tType || !ags) return null;
    const requirements = new Map();
    ags.forEach(agent => {
      const test = agent.supportedTests?.find(t => t.testType === tType);
      if (test) {
        test.requiredPayloadTypes?.forEach(r => requirements.set(r, 'REQUIRED'));
        test.optionalPayloadTypes?.forEach(o => {
          if (requirements.get(o) !== 'REQUIRED') {
            requirements.set(o, 'RECOMMENDED');
          }
        });
      }
    });
    return requirements.get(payloadType) || null;
  };

  const handleCheck = (payloadId, checked) => {
    if (checked) {
      if (!payloadIds.includes(payloadId)) {
        payloadIds = [...payloadIds, payloadId];
      }
    } else {
      payloadIds = payloadIds.filter(val => val !== payloadId);
    }
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    errorMsg = null;

    if (!name) {
      errorMsg = "Name is required";
      return;
    }
    if (!testType) {
      errorMsg = "Type is required";
      return;
    }

    $saveMutation.mutate({
      name,
      description,
      testType,
      payloadIds
    });
  };

  let isLoading = $derived($contextQuery.isPending);
  let hasError = $derived($contextQuery.isError);
  let errorMessage = $derived($contextQuery.error?.message || String($contextQuery.error));
</script>

<div class="max-w-3xl mx-auto w-full space-y-6">
  {#if isLoading}
    <div class="flex flex-col items-center justify-center min-h-[30vh] gap-3">
      <Loader2 class="animate-spin w-8 h-8 text-primary-500" />
      <p class="text-sm text-surface-500">Loading Form data...</p>
    </div>
  {:else if hasError}
    <div class="alert preset-tonal-error p-4 rounded-lg">
      <span class="font-medium">Error loading test data:</span> {errorMessage}
    </div>
  {:else}
    <div class="space-y-6">
      <!-- Header -->
      <div class="flex justify-between items-center">
        <h1 class="text-2xl font-bold tracking-tight">
          {isEdit ? 'Edit Test' : 'New Test'}
        </h1>
        <div class="flex gap-2">
          {#if isEdit}
            <button
              class="btn btn-sm preset-tonal-surface-500 flex items-center gap-2"
              disabled={$copyMutation.isPending}
              onclick={() => $copyMutation.mutate()}
            >
              {#if $copyMutation.isPending}
                <Loader2 class="animate-spin" size={16} />
              {:else}
                <Copy size={16} />
              {/if}
              Copy
            </button>
          {/if}
          <button 
            class="btn btn-sm preset-tonal-surface-500 flex items-center gap-2"
            onclick={() => navigate('/tests')}
          >
            <ArrowLeft size={16} />
            Return
          </button>
        </div>
      </div>

      <!-- Error banner -->
      {#if errorMsg}
        <div class="alert preset-tonal-error p-4 rounded-lg">
          {errorMsg}
        </div>
      {/if}

      <form class="space-y-6" onsubmit={handleSubmit}>
        <!-- Settings Card -->
        <div class="card p-6 bg-surface-100 dark:bg-surface-900 border border-surface-200 dark:border-surface-800 rounded-lg shadow-sm">
          <h2 class="text-lg font-semibold text-surface-900 dark:text-white mb-4">Settings</h2>

          <div class="space-y-4">
            <div class="w-full">
              <label for="test-name" class="block text-sm font-medium mb-1 text-surface-700 dark:text-surface-300">Name <span class="text-error-500">*</span></label>
              <input
                id="test-name"
                type="text"
                bind:value={name}
                placeholder="Enter test name"
                required
                class="input p-2 rounded-lg bg-surface-50 dark:bg-surface-950 border border-surface-300 dark:border-surface-850 w-full"
              />
            </div>

            <div class="w-full">
              <label for="test-description" class="block text-sm font-medium mb-1 text-surface-700 dark:text-surface-300">Description</label>
              <textarea
                id="test-description"
                bind:value={description}
                placeholder="Enter description"
                rows="3"
                class="textarea p-2 rounded-lg bg-surface-50 dark:bg-surface-950 border border-surface-300 dark:border-surface-850 w-full"
              ></textarea>
            </div>

            <div class="w-full">
              <label for="test-type" class="block text-sm font-medium mb-1 text-surface-700 dark:text-surface-300">Type <span class="text-error-500">*</span></label>
              <input
                id="test-type"
                type="text"
                bind:value={testType}
                placeholder="Select or enter test type"
                required
                class="input p-2 rounded-lg bg-surface-50 dark:bg-surface-950 border border-surface-300 dark:border-surface-850 w-full"
                list="available-test-types"
              />
              <datalist id="available-test-types">
                {#each availableTypes as item}
                  <option value={item}></option>
                {/each}
              </datalist>
            </div>
          </div>
        </div>

        <!-- Payloads Card -->
        <div class="card p-6 bg-surface-100 dark:bg-surface-900 border border-surface-200 dark:border-surface-800 rounded-lg shadow-sm">
          <h2 class="text-lg font-semibold text-surface-900 dark:text-white mb-4">Payloads</h2>

          <div class="space-y-2 max-h-[300px] overflow-y-auto pr-1">
            {#if allPayloads.length === 0}
              <div class="text-center py-6 text-sm text-surface-500">
                <span>Empty. </span>
                <button class="btn btn-sm preset-tonal-surface-500" onclick={() => navigate('/payloads/new')}>New</button>
              </div>
            {:else}
              <div class="space-y-2">
                {#each allPayloads as payload (payload.id)}
                  {@const isChecked = payloadIds.includes(payload.id)}
                  {@const req = getPayloadRequirement(payload.type)}
                  <div 
                    class="flex items-center justify-between p-3 rounded-lg border transition-colors {isChecked ? 'bg-primary-500/10 border-primary-500/30' : 'bg-surface-50 dark:bg-surface-950 border-surface-250 dark:border-surface-850'}"
                  >
                    <label class="cursor-pointer flex justify-start items-center gap-3 w-full select-none">
                      <input 
                        type="checkbox"
                        checked={isChecked}
                        class="checkbox accent-primary-500"
                        onchange={(e) => handleCheck(payload.id, e.target.checked)}
                      />
                      <div class="flex flex-col">
                        <span class="font-semibold text-sm text-surface-950 dark:text-white">{payload.name}</span>
                        <span class="font-mono text-xs text-surface-400">{payload.type}</span>
                      </div>
                    </label>
                    
                    {#if req}
                      <span class="badge {req === 'REQUIRED' ? 'preset-filled-error-500' : 'preset-filled-success-500'} shrink-0 text-[10px] px-1.5 py-0.5 font-semibold">
                        {req}
                      </span>
                    {/if}
                  </div>
                {/each}
              </div>
            {/if}
          </div>
        </div>

        <button
          type="submit"
          class="btn btn-sm preset-filled-primary-500 w-full flex justify-center gap-2"
          disabled={$saveMutation.isPending}
        >
          {#if $saveMutation.isPending}
            <Loader2 class="animate-spin" size={18} />
          {:else}
            <Save size={18} />
          {/if}
          Save
        </button>
      </form>
    </div>
  {/if}
</div>
