// src/main/webui/src/pages/Translations.vue
<script setup>
import { computed } from 'vue';
import { useQuery } from '@tanstack/vue-query';
import { safeFetch } from '@/utils/safeFetch';
import { getCleanStatus, getStatusColor } from '@/utils/format';
import { useRouter } from 'vue-router';

const router = useRouter();

const { data: sessionsData, isPending: isLoading, error: hasError } = useQuery({
  queryKey: ['sessions'],
  queryFn: () => safeFetch('/api/translations/sessions').then(res => {
    if (!Array.isArray(res)) {
      throw new Error("API returned invalid data format");
    }
    return res;
  })
});

const sessions = computed(() => sessionsData.value || []);
const errorMessage = computed(() => hasError.value?.message || String(hasError.value));

const mapColor = (status) => {
  const col = getStatusColor(status);
  if (col === 'danger') return 'error';
  if (col === 'secondary') return 'neutral';
  return col;
};
</script>

<template>
  <div class="space-y-6 w-full">
    <!-- Header -->
    <div class="flex justify-between items-center">
      <h1 class="text-2xl font-bold tracking-tight">
        Translations
      </h1>
      <UButton 
        label="New" 
        size="sm" 
        icon="i-lucide-plus"
        @click="router.push('/translations/new')"
      />
    </div>

    <!-- Loading State -->
    <div
      v-if="isLoading"
      class="flex justify-center py-12"
    >
      <UIcon name="i-lucide-loader-2" class="animate-spin w-10 h-10 text-primary-500" />
    </div>

    <!-- Error State -->
    <UAlert
      v-else-if="hasError"
      title="Error loading translation sessions"
      :description="errorMessage"
      color="error"
      variant="solid"
      class="w-full"
    />

    <div
      v-else
      class="space-y-6"
    >
      <!-- Empty State -->
      <UCard
        v-if="sessions.length === 0"
        class="text-center py-8 shadow-sm"
      >
        <p class="text-gray-500 text-sm">
          No active translation sessions.
        </p>
        <div class="flex justify-center mt-3">
          <UButton 
            label="Start one" 
            variant="link" 
            size="sm" 
            @click="router.push('/translations/new')"
          />
        </div>
      </UCard>

      <!-- Grid View -->
      <div
        v-else
        class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6"
      >
        <UCard 
          v-for="session in sessions" 
          :key="session.sessionId"
          class="hover:shadow-md transition-shadow flex flex-col justify-between"
          :ui="{ body: 'flex-grow flex flex-col justify-between p-5' }"
        >
          <div class="space-y-4">
            <!-- Session Title & ID -->
            <div class="flex justify-between items-start gap-4">
              <div class="min-w-0">
                <h3 
                  class="font-semibold text-base truncate text-gray-800 dark:text-gray-200"
                  :title="session.ticket?.testType || session.agentName"
                >
                  {{ session.ticket?.testType || session.agentName }}
                </h3>
                <span class="font-mono text-xs text-gray-400 block mt-0.5 truncate">
                  {{ session.sessionId }}
                </span>
              </div>
              <UBadge 
                :color="mapColor(session.status)"
                variant="subtle"
                size="sm"
              >
                {{ getCleanStatus(session.status) }}
              </UBadge>
            </div>

            <!-- Details -->
            <div class="grid grid-cols-2 gap-2 text-xs text-gray-650 dark:text-gray-400 bg-gray-50 dark:bg-gray-900/50 p-2.5 rounded-lg border border-gray-100 dark:border-gray-800/80">
              <div>
                <span class="text-gray-400 block">System:</span>
                <span class="font-medium text-gray-700 dark:text-gray-300">{{ session.systemId || 'N/A' }}</span>
              </div>
              <div>
                <span class="text-gray-400 block">Agent:</span>
                <span
                  class="font-medium truncate block text-gray-700 dark:text-gray-300"
                  :title="session.agentName"
                >{{ session.agentName || 'N/A' }}</span>
              </div>
            </div>

            <!-- Status Message -->
            <div class="flex items-center gap-1.5 min-w-0">
              <span 
                class="inline-block w-1.5 h-1.5 rounded-full shrink-0"
                :class="session.status === 'RUNNING' ? 'bg-primary-500 animate-pulse' : 'bg-gray-300 dark:bg-gray-700'"
              />
              <span
                v-if="session.statusMessage"
                class="text-xs text-gray-400 truncate"
                :title="session.statusMessage"
              >
                {{ session.statusMessage }}
              </span>
            </div>
          </div>
          
          <USeparator class="my-4" />
          
          <div class="flex justify-end">
            <UButton 
              label="Monitor" 
              color="neutral" 
              variant="outline" 
              size="sm" 
              icon="i-lucide-chevron-right"
              @click="router.push(`/translations/${session.sessionId}/status`)"
            />
          </div>
        </UCard>
      </div>
    </div>
  </div>
</template>

// src/main/webui/src/pages/Translations.svelte
<script>
  import { useTranslationSessionsQuery } from '@/composables/queries.svelte';
  import { getCleanStatus, getStatusColor } from '@/utils/format';
  import { navigate } from '@/router.js';
  import ChevronRight from '@lucide/svelte/icons/chevron-right';
import Plus from '@lucide/svelte/icons/plus';
import Loader2 from '@lucide/svelte/icons/loader-2';

  const sessionsQuery = useTranslationSessionsQuery();

  let isLoading = $derived(sessionsQuery.isPending);
  let hasError = $derived(sessionsQuery.error);
  let errorMessage = $derived(sessionsQuery.error?.message || String(sessionsQuery.error));
  let sessions = $derived(sessionsQuery.data || []);

  const getBadgePreset = (status) => {
    const col = getStatusColor(status);
    if (col === 'danger') return 'preset-filled-error-500';
    if (col === 'secondary') return 'preset-tonal-surface-500';
    if (col === 'success') return 'preset-filled-success-500';
    if (col === 'info') return 'preset-filled-primary-500';
    if (col === 'warning') return 'preset-filled-warning-500';
    return 'preset-tonal-surface-500';
  };
</script>

<div class="space-y-6 w-full">
  <!-- Header -->
  <div class="flex justify-between items-center">
    <h1 class="text-2xl font-bold tracking-tight">Translations</h1>
    <button 
      class="btn btn-sm preset-filled-primary-500 flex items-center gap-2"
      onclick={() => navigate('/translations/new')}
    >
      <Plus size={16} />
      New
    </button>
  </div>

  <!-- Content -->
  {#if isLoading}
    <div class="flex flex-col items-center justify-center min-h-[30vh] gap-3">
      <Loader2 class="animate-spin w-8 h-8 text-primary-500" />
      <p class="text-sm text-surface-500">Loading sessions...</p>
    </div>
  {:else if hasError}
    <div class="alert preset-tonal-error p-4 rounded-lg">
      <span class="font-medium">Error loading translations:</span> {errorMessage}
    </div>
  {:else if sessions.length === 0}
    <div class="card p-8 bg-surface-100 dark:bg-surface-900 border border-surface-200 dark:border-surface-800 rounded-lg text-center">
      <p class="text-surface-500 text-sm">No translation sessions.</p>
      <div class="flex justify-center mt-3">
        <button class="btn btn-sm preset-tonal-surface-500 btn-sm" onclick={() => navigate('/translations/new')}>
          Create New
        </button>
      </div>
    </div>
  {:else}
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
      {#each sessions as session (session.sessionId)}
        <div class="card p-5 bg-surface-100 dark:bg-surface-900 border border-surface-200 dark:border-surface-800 rounded-lg shadow-sm flex flex-col justify-between">
          <div class="space-y-4">
            <!-- Session Title & ID -->
            <div class="flex justify-between items-start gap-4">
              <div class="min-w-0">
                <h3 class="font-semibold text-base truncate text-surface-800 dark:text-surface-200" title={session.ticket?.testType || session.agentName}>
                  {session.ticket?.testType || session.agentName}
                </h3>
                <span class="font-mono text-xs text-surface-400 block mt-0.5 truncate">
                  {session.sessionId}
                </span>
              </div>
              <span class="badge {getBadgePreset(session.status)} text-[10px] px-1.5 py-0.5 font-semibold">
                {getCleanStatus(session.status)}
              </span>
            </div>

            <!-- Details -->
            <div class="grid grid-cols-2 gap-2 text-xs text-surface-500 dark:text-surface-400 bg-surface-50 dark:bg-surface-950 p-2.5 rounded-lg border border-surface-250 dark:border-surface-850">
              <div>
                <span class="text-surface-400 block">Agent ID:</span>
                <span class="font-medium text-surface-950 dark:text-white">{session.agentId || 'N/A'}</span>
              </div>
              <div>
                <span class="text-surface-400 block">Agent Name:</span>
                <span class="font-medium text-surface-950 dark:text-white truncate block" title={session.agentName}>
                  {session.agentName || 'N/A'}
                </span>
              </div>
            </div>

            <!-- Status Message -->
            <div class="flex items-center gap-1.5 min-w-0">
              <span 
                class="inline-block w-1.5 h-1.5 rounded-full shrink-0 {session.status === 'RUNNING' ? 'bg-primary-500 animate-pulse' : 'bg-surface-300'}"
              ></span>
              {#if session.statusMessage}
                <span class="text-xs text-surface-400 truncate" title={session.statusMessage}>
                  {session.statusMessage}
                </span>
              {/if}
            </div>
          </div>
          
          <hr class="my-4 border-surface-250 dark:border-surface-800" />
          
          <div class="flex justify-end">
            <button 
              class="btn btn-sm preset-tonal-surface-500 flex items-center gap-1"
              onclick={() => navigate(`/translations/${session.sessionId}/status`)}
            >
              <span>Monitor</span>
              <ChevronRight size={14} />
            </button>
          </div>
        </div>
      {/each}
    </div>
  {/if}
</div>
