// src/main/webui/src/pages/Translations.jsx
import { createQuery } from '@tanstack/solid-query';
import { safeFetch } from '../utils/safeFetch';
import { getCleanStatus, getStatusColor } from '../utils/format';
import { useNavigate } from '@solidjs/router';
import { Plus } from 'lucide-solid';
import { Show, For, createEffect } from 'solid-js';
import { Title } from '@solidjs/meta';

export default function Translations() {
    const navigate = useNavigate();

    const sessionsQuery = createQuery(() => ({
        queryKey: ['translationsSessions'],
        queryFn: () => safeFetch('/api/translations/sessions').then(res => {
            if (!Array.isArray(res)) {
                throw new Error("API returned invalid data format");
            }
            return res;
        })
    }));

    const sessions = () => sessionsQuery.data || [];
    const isLoading = () => sessionsQuery.isPending;
    const hasError = () => sessionsQuery.error;
    const errorMessage = () => sessionsQuery.error?.message || String(sessionsQuery.error);

    return (
        <div class="space-y-6 w-full">
            <Title>Translations | TestState</Title>
            {/* Header */}
            <div class="flex justify-between items-center">
                <h1 class="text-2xl font-bold">Translations</h1>
                <button 
                    class="btn btn-primary btn-sm flex items-center gap-1.5" 
                    onClick={() => navigate('/translations/new')}
                >
                    <Plus size={16} />
                    <span>New</span>
                </button>
            </div>

            {/* Content states */}
            <Show when={isLoading()}>
                <div class="flex flex-col items-center justify-center min-h-[30vh] gap-3">
                    <span class="loading loading-spinner loading-md text-primary"></span>
                    <p class="text-sm text-base-content/60">Loading translation logs...</p>
                </div>
            </Show>

            <Show when={!isLoading() && hasError()}>
                <div class="alert alert-error">
                    <span>Error: {errorMessage()}</span>
                </div>
            </Show>

            <Show when={!isLoading() && !hasError()}>
                <Show when={sessions().length === 0}>
                    <div class="card bg-base-100 border border-base-200 shadow-sm p-8 text-center space-y-3">
                        <p class="text-base-content/60 text-sm">No active translation sessions.</p>
                        <div class="flex justify-center">
                            <button class="btn btn-ghost btn-sm text-primary" onClick={() => navigate('/translations/new')}>
                                Start one
                            </button>
                        </div>
                    </div>
                </Show>

                <Show when={sessions().length > 0}>
                    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                        <For each={sessions()}>
                            {(session) => (
                                <div class="card bg-base-100 border border-base-200 shadow-sm hover:shadow-md transition-shadow flex flex-col justify-between">
                                    <div class="card-body p-5 gap-3 flex-grow">
                                        <div class="flex justify-between items-center gap-4">
                                            <span class="font-mono text-xs text-base-content/50 truncate flex-grow" title={session.sessionId}>
                                                {session.sessionId}
                                            </span>
                                            <Show when={session.format}>
                                                <span class="badge badge-info badge-sm shrink-0">
                                                    {session.format}
                                                </span>
                                            </Show>
                                        </div>
                                        <div class="flex items-center gap-2 flex-wrap">
                                            <span class={`badge badge-sm ${getStatusColor(session.status)}`}>
                                                {getCleanStatus(session.status)}
                                            </span>
                                            <Show when={session.statusMessage}>
                                                <span class="text-xs text-base-content/60 truncate" title={session.statusMessage}>
                                                    ({session.statusMessage})
                                                </span>
                                            </Show>
                                        </div>
                                    </div>
                                    <div class="px-5 pb-5">
                                        <div class="h-[1px] bg-base-200 mb-4" />
                                        <div class="flex justify-end">
                                            <button 
                                                class="btn btn-xs btn-outline" 
                                                onClick={() => navigate(`/translations/${session.sessionId}/status`)}
                                            >
                                                Monitor
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            )}
                        </For>
                    </div>
                </Show>
            </Show>
        </div>
    );
}

// src/main/webui/src/pages/Translations.vue
<script setup>
import { computed } from 'vue';
import { useQuery } from '@tanstack/vue-query';
import { safeFetch } from '@/utils/safeFetch';
import { getCleanStatus, getStatusColor } from '@/utils/format';
import { useRouter } from 'vue-router';

const router = useRouter();

const { data: sessionsData, isPending: isLoading, error: hasError } = useQuery({
  queryKey: ['sessions'],
  queryFn: () => safeFetch('/api/translations/sessions').then(res => {
    if (!Array.isArray(res)) {
      throw new Error("API returned invalid data format");
    }
    return res;
  })
});

const sessions = computed(() => sessionsData.value || []);
const errorMessage = computed(() => hasError.value?.message || String(hasError.value));

const mapColor = (status) => {
  const col = getStatusColor(status);
  if (col === 'danger') return 'error';
  if (col === 'secondary') return 'neutral';
  return col;
};
</script>

<template>
  <div class="space-y-6 w-full">
    <!-- Header -->
    <div class="flex justify-between items-center">
      <h1 class="text-2xl font-bold tracking-tight">
        Translations
      </h1>
      <UButton 
        label="New" 
        size="sm" 
        icon="i-lucide-plus"
        @click="router.push('/translations/new')"
      />
    </div>

    <!-- Loading State -->
    <div
      v-if="isLoading"
      class="flex justify-center py-12"
    >
      <UIcon name="i-lucide-loader-2" class="animate-spin w-10 h-10 text-primary-500" />
    </div>

    <!-- Error State -->
    <UAlert
      v-else-if="hasError"
      title="Error loading translation sessions"
      :description="errorMessage"
      color="error"
      variant="solid"
      class="w-full"
    />

    <div
      v-else
      class="space-y-6"
    >
      <!-- Empty State -->
      <UCard
        v-if="sessions.length === 0"
        class="text-center py-8 shadow-sm"
      >
        <p class="text-gray-500 text-sm">
          No active translation sessions.
        </p>
        <div class="flex justify-center mt-3">
          <UButton 
            label="Start one" 
            variant="link" 
            size="sm" 
            @click="router.push('/translations/new')"
          />
        </div>
      </UCard>

      <!-- Grid View -->
      <div
        v-else
        class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6"
      >
        <UCard 
          v-for="session in sessions" 
          :key="session.sessionId"
          class="hover:shadow-md transition-shadow flex flex-col justify-between"
          :ui="{ body: 'flex-grow flex flex-col justify-between p-5' }"
        >
          <div class="space-y-4">
            <!-- Session Title & ID -->
            <div class="flex justify-between items-start gap-4">
              <div class="min-w-0">
                <h3 
                  class="font-semibold text-base truncate text-gray-800 dark:text-gray-200"
                  :title="session.ticket?.testType || session.agentName"
                >
                  {{ session.ticket?.testType || session.agentName }}
                </h3>
                <span class="font-mono text-xs text-gray-400 block mt-0.5 truncate">
                  {{ session.sessionId }}
                </span>
              </div>
              <UBadge 
                :color="mapColor(session.status)"
                variant="subtle"
                size="sm"
              >
                {{ getCleanStatus(session.status) }}
              </UBadge>
            </div>

            <!-- Details -->
            <div class="grid grid-cols-2 gap-2 text-xs text-gray-650 dark:text-gray-400 bg-gray-50 dark:bg-gray-900/50 p-2.5 rounded-lg border border-gray-100 dark:border-gray-800/80">
              <div>
                <span class="text-gray-400 block">System:</span>
                <span class="font-medium text-gray-700 dark:text-gray-300">{{ session.systemId || 'N/A' }}</span>
              </div>
              <div>
                <span class="text-gray-400 block">Agent:</span>
                <span
                  class="font-medium truncate block text-gray-700 dark:text-gray-300"
                  :title="session.agentName"
                >{{ session.agentName || 'N/A' }}</span>
              </div>
            </div>

            <!-- Status Message -->
            <div class="flex items-center gap-1.5 min-w-0">
              <span 
                class="inline-block w-1.5 h-1.5 rounded-full shrink-0"
                :class="session.status === 'RUNNING' ? 'bg-primary-500 animate-pulse' : 'bg-gray-300 dark:bg-gray-700'"
              />
              <span
                v-if="session.statusMessage"
                class="text-xs text-gray-400 truncate"
                :title="session.statusMessage"
              >
                {{ session.statusMessage }}
              </span>
            </div>
          </div>
          
          <USeparator class="my-4" />
          
          <div class="flex justify-end">
            <UButton 
              label="Monitor" 
              color="neutral" 
              variant="outline" 
              size="sm" 
              icon="i-lucide-chevron-right"
              @click="router.push(`/translations/${session.sessionId}/status`)"
            />
          </div>
        </UCard>
      </div>
    </div>
  </div>
</template>
