// src/main/webui/src/pages/TranslationForm.jsx
import { createSignal, createEffect, Show, For } from 'solid-js';
import { Title } from '@solidjs/meta';
import { safeFetch } from '../utils/safeFetch';
import { useNavigate } from '@solidjs/router';
import { createMutation, createQuery, useQueryClient } from '@tanstack/solid-query';
import { ArrowLeft, Play } from 'lucide-solid';

export default function TranslationForm() {
    const navigate = useNavigate();
    const queryClient = useQueryClient();
    const [formError, setFormError] = createSignal(null);

    const [agentId, setAgentId] = createSignal('');
    const [type, setType] = createSignal('');
    const [payloadIds, setPayloadIds] = createSignal([]);

    const agentsQuery = createQuery(() => ({
        queryKey: ['agents'],
        queryFn: () => safeFetch('/api/agents')
    }));

    const payloadsQuery = createQuery(() => ({
        queryKey: ['payloads'],
        queryFn: () => safeFetch('/api/payloads')
    }));

    const mutation = createMutation(() => ({
        mutationFn: (body) => safeFetch('/api/translations/sessions', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json'
            },
            body: JSON.stringify(body)
        }),
        onSuccess: (res) => {
            queryClient.invalidateQueries({ queryKey: ['translationsSessions'] });
            if (res.sessionId) {
                navigate(`/translations/${res.sessionId}/status`);
            }
        },
        onError: (err) => {
            setFormError(err.message);
        }
    }));

    const agents = () => agentsQuery.data || [];
    const payloads = () => payloadsQuery.data || [];

    const currentAgent = () => agents().find(a => a.id === agentId());
    const currentTranslation = () => currentAgent()?.supportedTranslations?.find(t => t.type === type());
    const allowedSources = () => currentTranslation()?.sourcePayloadTypes || [];

    const filteredPayloads = () => {
        const t = type();
        const pl = payloads();
        const sources = allowedSources();
        return t ? pl.filter(p => sources.includes(p.type)) : pl;
    };

    const handleAgentChange = (value) => {
        setAgentId(value || '');
        setType('');
        setPayloadIds([]);
    };

    const handleTypeChange = (value) => {
        setType(value || '');
        setPayloadIds([]);
    };

    createEffect(() => {
        const t = type();
        const ids = payloadIds();
        const pl = payloads();
        const sources = allowedSources();

        if (t && ids.length > 0) {
            const validIds = ids.filter(id => {
                const p = pl.find(x => x.id === id);
                return p && sources.includes(p.type);
            });
            if (validIds.length !== ids.length) {
                setPayloadIds(validIds);
            }
        }
    });

    const handleSubmit = (e) => {
        e.preventDefault();
        const agId = agentId();
        const t = type();
        if (!agId) {
            setFormError('Please select a translation node.');
            return;
        }
        if (!t) {
            setFormError('Please select a translation type.');
            return;
        }
        setFormError(null);
        mutation.mutate({
            agentId: agId,
            type: t,
            payloadIds: payloadIds()
        });
    };

    const handlePayloadCheck = (id, checked) => {
        if (checked) {
            setPayloadIds(prev => [...prev, id]);
        } else {
            setPayloadIds(prev => prev.filter(val => val !== id));
        }
    };

    const isLoading = () => agentsQuery.isPending || payloadsQuery.isPending;
    const error = () => formError() || mutation.error?.message;

    return (
        <div class="max-w-3xl mx-auto w-full space-y-6">
            <Title>Create Translation | TestState</Title>
            {/* Header */}
            <div class="flex justify-between items-center">
                <h1 class="text-2xl font-bold">New Translation</h1>
                <button
                    class="btn btn-outline btn-sm flex items-center gap-1.5"
                    onClick={() => navigate('/translations')}
                >
                    <ArrowLeft size={16} />
                    <span>Cancel</span>
                </button>
            </div>

            <Show when={error()}>
                <div class="alert alert-error flex justify-between items-center">
                    <span>{error()}</span>
                    <button class="btn btn-ghost btn-xs text-error-content" onClick={() => setFormError(null)}>✕</button>
                </div>
            </Show>

            <Show when={isLoading()}>
                <div class="flex flex-col items-center justify-center min-h-[30vh] gap-3">
                    <span class="loading loading-spinner loading-md text-primary"></span>
                    <p class="text-sm text-base-content/60">Loading translation profiles...</p>
                </div>
            </Show>

            <Show when={!isLoading()}>
                <form onSubmit={handleSubmit} class="space-y-6">
                    {/* Task Card */}
                    <div class="card bg-base-100 border border-base-200 shadow-sm">
                        <div class="card-body p-5 space-y-4">
                            <h2 class="card-title text-base font-semibold border-b border-base-200 pb-2">Task</h2>

                            <div class="form-control w-full">
                                <label class="label">
                                    <span class="label-text font-semibold">Node <span class="text-error">*</span></span>
                                </label>
                                <select 
                                    class="select select-bordered w-full"
                                    value={agentId()}
                                    onChange={(e) => handleAgentChange(e.currentTarget.value)}
                                >
                                    <option value="" disabled selected>Select translation node</option>
                                    <For each={agents()}>
                                        {(agent) => <option value={agent.id}>{agent.name}</option>}
                                    </For>
                                </select>
                            </div>

                            <div class="form-control w-full">
                                <label class="label">
                                    <span class="label-text font-semibold">Type <span class="text-error">*</span></span>
                                </label>
                                <select 
                                    class="select select-bordered w-full"
                                    disabled={!agentId()}
                                    value={type()}
                                    onChange={(e) => handleTypeChange(e.currentTarget.value)}
                                >
                                    <option value="" disabled selected>
                                        {agentId() ? "Select translation format type" : "Select node first"}
                                    </option>
                                    <For each={currentAgent()?.supportedTranslations || []}>
                                        {(trans) => <option value={trans.type}>{trans.type}</option>}
                                    </For>
                                </select>
                            </div>

                            <Show when={currentTranslation()}>
                                <div class="flex items-center gap-2 font-mono text-xs mt-2">
                                    <span class="badge badge-accent badge-sm">{allowedSources().join(', ')}</span>
                                    <span>&rarr;</span>
                                    <span class="badge badge-secondary badge-sm">{currentTranslation().targetPayloadTypes?.join(', ')}</span>
                                </div>
                            </Show>
                        </div>
                    </div>

                    {/* Payloads Card */}
                    <div class="card bg-base-100 border border-base-200 shadow-sm">
                        <div class="card-body p-5 space-y-4">
                            <h2 class="card-title text-base font-semibold border-b border-base-200 pb-2">Payloads</h2>
                            <div class="space-y-2 max-h-[240px] overflow-y-auto pr-1">
                                <Show when={filteredPayloads().length === 0}>
                                    <p class="text-center text-sm text-base-content/50 py-4">No compatible payloads.</p>
                                </Show>
                                <Show when={filteredPayloads().length > 0}>
                                    <div class="space-y-2">
                                        <For each={filteredPayloads()}>
                                            {(payload) => {
                                                const isChecked = () => payloadIds().includes(payload.id);
                                                return (
                                                    <div 
                                                        class={`flex items-center justify-between p-3 rounded-lg border border-base-200 transition-colors ${
                                                            isChecked() ? 'bg-primary/5 border-primary/20' : 'bg-base-300/40'
                                                        }`}
                                                    >
                                                        <label class="label cursor-pointer flex justify-start items-center gap-3 w-full">
                                                            <input 
                                                                type="checkbox" 
                                                                class="checkbox checkbox-primary checkbox-sm"
                                                                checked={isChecked()}
                                                                onChange={(e) => handlePayloadCheck(payload.id, e.currentTarget.checked)}
                                                            />
                                                            <div class="flex flex-col">
                                                                <span class="font-semibold text-sm">{payload.name}</span>
                                                                <span class="font-mono text-xs text-base-content/50">{payload.type}</span>
                                                            </div>
                                                        </label>
                                                    </div>
                                                );
                                            }}
                                        </For>
                                    </div>
                                </Show>
                            </div>
                        </div>
                    </div>

                    <button
                        type="submit"
                        class="btn btn-primary w-full flex items-center gap-2"
                        disabled={!type() || mutation.isPending}
                    >
                        <Show when={mutation.isPending}>
                            <span class="loading loading-spinner loading-sm"></span>
                        </Show>
                        <Show when={!mutation.isPending}>
                            <Play size={18} />
                        </Show>
                        <span>Start Translation</span>
                    </button>
                </form>
            </Show>
        </div>
    );
}

// src/main/webui/src/pages/TranslationForm.svelte
<script>
  import { createQuery, createMutation, useQueryClient } from '@tanstack/svelte-query';
  import { safeFetch } from '@/utils/safeFetch';
  import { navigate } from '@/router.js';
  import ArrowLeft from '@lucide/svelte/icons/arrow-left';
import Play from '@lucide/svelte/icons/play';
import Loader2 from '@lucide/svelte/icons/loader-2';

  const queryClient = useQueryClient();
  let formError = $state(null);

  let agentId = $state('');
  let type = $state('');
  let payloadIds = $state([]);

  const agentsQuery = createQuery(() => ({
    queryKey: ['agents'],
    queryFn: () => safeFetch('/api/agents')
  }));

  const payloadsQuery = createQuery(() => ({
    queryKey: ['payloads'],
    queryFn: () => safeFetch('/api/payloads')
  }));

  const mutation = createMutation(() => ({
    mutationFn: (body) => safeFetch('/api/translations/sessions', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify(body)
    }),
    onSuccess: (res) => {
      queryClient.invalidateQueries({ queryKey: ['translationsSessions'] });
      if (res.sessionId) {
        navigate(`/translations/${res.sessionId}/status`);
      }
    },
    onError: (err) => {
      formError = err.message;
    }
  }));

  let agents = $derived(agentsQuery.data || []);
  let payloads = $derived(payloadsQuery.data || []);

  let currentAgent = $derived(agents.find(a => a.id === agentId));
  let currentTranslation = $derived(currentAgent?.supportedTranslations?.find(t => t.type === type));
  let allowedSources = $derived(currentTranslation?.sourcePayloadTypes || []);

  let filteredPayloads = $derived(
    type ? payloads.filter(p => allowedSources.includes(p.type)) : payloads
  );

  const handleAgentChange = () => {
    type = '';
    payloadIds = [];
  };

  const handleTypeChange = () => {
    payloadIds = [];
  };

  $effect(() => {
    if (type && payloadIds.length > 0) {
      const validIds = payloadIds.filter(id => {
        const p = payloads.find(x => x.id === id);
        return p && allowedSources.includes(p.type);
      });
      if (validIds.length !== payloadIds.length) {
        payloadIds = validIds;
      }
    }
  });

  const handleSubmit = (e) => {
    e.preventDefault();
    if (!agentId) {
      formError = 'Please select a translation node.';
      return;
    }
    if (!type) {
      formError = 'Please select a translation type.';
      return;
    }
    formError = null;
    mutation.mutate({
      agentId,
      type,
      payloadIds
    });
  };

  const handlePayloadCheck = (id, checked) => {
    if (checked) {
      if (!payloadIds.includes(id)) {
        payloadIds = [...payloadIds, id];
      }
    } else {
      payloadIds = payloadIds.filter(val => val !== id);
    }
  };

  let isLoading = $derived(agentsQuery.isPending || payloadsQuery.isPending);
  let error = $derived(formError || mutation.error?.message);

  let agentOptions = $derived(agents.map(a => ({ label: a.name, value: a.id })));
  let typeOptions = $derived((currentAgent?.supportedTranslations || []).map(t => ({ label: t.type, value: t.type })));
</script>

<div class="max-w-3xl mx-auto w-full space-y-6">
  <!-- Header -->
  <div class="flex justify-between items-center">
    <h1 class="text-2xl font-bold tracking-tight">New Translation</h1>
    <button 
      class="btn btn-sm preset-tonal-surface-500 flex items-center gap-2"
      onclick={() => navigate('/translations')}
    >
      <ArrowLeft size={16} />
      Cancel
    </button>
  </div>

  <!-- Error Banner -->
  {#if error}
    <div class="alert preset-tonal-error p-4 rounded-lg">
      {error}
    </div>
  {/if}

  <!-- Loading State -->
  {#if isLoading}
    <div class="flex flex-col items-center justify-center min-h-[30vh] gap-3">
      <Loader2 class="animate-spin w-8 h-8 text-primary-500" />
      <p class="text-sm text-surface-500">Loading translation profiles...</p>
    </div>
  {:else}
    <form class="space-y-6" onsubmit={handleSubmit}>
      <!-- Task Card -->
      <div class="card p-6 bg-surface-100 dark:bg-surface-900 border border-surface-200 dark:border-surface-800 rounded-lg shadow-sm">
        <h2 class="text-lg font-semibold text-surface-900 dark:text-white mb-4">Task</h2>

        <div class="space-y-4">
          <div class="w-full">
            <label for="translation-node" class="block text-sm font-medium mb-1 text-surface-700 dark:text-surface-300">Node <span class="text-error-500">*</span></label>
            <select 
              id="translation-node"
              bind:value={agentId}
              onchange={handleAgentChange}
              class="select p-2 rounded-lg bg-surface-50 dark:bg-surface-950 border border-surface-300 dark:border-surface-850 w-full"
            >
              <option value="" disabled>Select translation node</option>
              {#each agentOptions as opt (opt.value)}
                <option value={opt.value}>{opt.label}</option>
              {/each}
            </select>
          </div>

          <div class="w-full">
            <label for="translation-type" class="block text-sm font-medium mb-1 text-surface-700 dark:text-surface-300">Type <span class="text-error-500">*</span></label>
            <select 
              id="translation-type"
              bind:value={type}
              disabled={!agentId}
              onchange={handleTypeChange}
              class="select p-2 rounded-lg bg-surface-50 dark:bg-surface-950 border border-surface-300 dark:border-surface-850 w-full"
            >
              <option value="" disabled>{agentId ? 'Select translation format type' : 'Select node first'}</option>
              {#each typeOptions as opt (opt.value)}
                <option value={opt.value}>{opt.label}</option>
              {/each}
            </select>
          </div>

          {#if currentTranslation}
            <div class="flex items-center gap-2 font-mono text-xs mt-2">
              <span class="badge preset-filled-primary-500 text-[10px] px-1.5 py-0.5">
                {allowedSources.join(', ')}
              </span>
              <span class="text-surface-400">&rarr;</span>
              <span class="badge preset-filled-success-500 text-[10px] px-1.5 py-0.5">
                {currentTranslation.targetPayloadTypes?.join(', ')}
              </span>
            </div>
          {/if}
        </div>
      </div>

      <!-- Payloads Card -->
      <div class="card p-6 bg-surface-100 dark:bg-surface-900 border border-surface-200 dark:border-surface-800 rounded-lg shadow-sm">
        <h2 class="text-lg font-semibold text-surface-900 dark:text-white mb-4">Payloads</h2>
        
        <div class="space-y-2 max-h-[240px] overflow-y-auto pr-1">
          {#if filteredPayloads.length === 0}
            <p class="text-center text-sm text-surface-500 py-4">No compatible payloads.</p>
          {:else}
            <div class="space-y-2">
              {#each filteredPayloads as payload (payload.id)}
                {@const isChecked = payloadIds.includes(payload.id)}
                <div 
                  class="flex items-center justify-between p-3 rounded-lg border transition-colors {isChecked ? 'bg-primary-500/10 border-primary-500/30' : 'bg-surface-50 dark:bg-surface-950 border-surface-250 dark:border-surface-850'}"
                >
                  <label class="cursor-pointer flex justify-start items-center gap-3 w-full select-none">
                    <input 
                      type="checkbox"
                      checked={isChecked}
                      class="checkbox accent-primary-500"
                      onchange={(e) => handlePayloadCheck(payload.id, e.target.checked)}
                    />
                    <div class="flex flex-col">
                      <span class="font-semibold text-sm text-surface-950 dark:text-white">{payload.name}</span>
                      <span class="font-mono text-xs text-surface-400">{payload.type}</span>
                    </div>
                  </label>
                </div>
              {/each}
            </div>
          {/if}
        </div>
      </div>

      <button
        type="submit"
        class="btn preset-filled-primary-500 w-full flex justify-center gap-2"
        disabled={!type || mutation.isPending}
      >
        {#if mutation.isPending}
          <Loader2 class="animate-spin" size={18} />
        {:else}
          <Play size={18} />
        {/if}
        Start Translation
      </button>
    </form>
  {/if}
</div>
