// src/main/webui/src/components/RecentActivity.vue
<script setup>
import { computed } from 'vue';
import { useRouter } from 'vue-router';
import { useBatchesQuery } from '@/composables/useBatchesQuery';
import { useSessionsQuery } from '@/composables/useSessionsQuery';
import { getCleanStatus, getStatusColor } from '@/utils/format';

const router = useRouter();

const batchesQuery = useBatchesQuery();
const sessionsQuery = useSessionsQuery();

const isLoading = computed(() => batchesQuery.isPending.value || sessionsQuery.isPending.value);
const hasError = computed(() => batchesQuery.error.value || sessionsQuery.error.value);
const errorMessage = computed(() => {
  const err = batchesQuery.error.value || sessionsQuery.error.value;
  return err ? (err.message || String(err)) : '';
});

const batches = computed(() => batchesQuery.data.value || []);
const sessions = computed(() => sessionsQuery.data.value || []);

const mapColor = (status) => {
  const col = getStatusColor(status);
  if (col === 'danger') return 'error';
  if (col === 'secondary') return 'neutral';
  return col;
};
</script>

<template>
  <div>
    <!-- Loading State -->
    <div
      v-if="isLoading"
      class="flex justify-center py-6"
    >
      <UIcon
        name="i-lucide-loader-2"
        class="animate-spin w-8 h-8 text-primary-500"
      />
    </div>

    <!-- Error State -->
    <UAlert
      v-else-if="hasError"
      title="Error loading recent activity"
      :description="errorMessage"
      color="error"
      variant="solid"
      class="w-full"
    />

    <div
      v-else
      class="grid grid-cols-1 lg:grid-cols-2 gap-6"
    >
      <!-- Batches -->
      <UCard class="shadow-sm">
        <template #header>
          <h2 class="text-base font-semibold">
            Recent Batches
          </h2>
        </template>
        
        <p
          v-if="batches.length === 0"
          class="text-center text-sm text-gray-500 py-4"
        >
          No batches
        </p>
        <div
          v-else
          class="divide-y divide-gray-200 dark:divide-gray-800"
        >
          <div 
            v-for="batch in batches.slice(0, 8)" 
            :key="batch.batchId"
            class="flex justify-between items-center py-3 first:pt-0 last:pb-0 gap-4"
          >
            <div class="min-w-0 flex-1">
              <h3
                class="font-semibold text-sm truncate text-gray-700 dark:text-gray-200"
                :title="batch.testName"
              >
                {{ batch.testName }}
              </h3>
              <div class="flex items-center gap-2 mt-1">
                <span class="font-mono text-xs text-gray-400">{{ batch.batchId }}</span>
                <UBadge
                  :color="mapColor(batch.status)"
                  variant="subtle"
                  size="sm"
                >
                  {{ getCleanStatus(batch.status) }}
                </UBadge>
              </div>
            </div>
            <UButton 
              label="Monitor" 
              variant="link" 
              size="sm" 
              class="p-0 font-semibold"
              @click="router.push(`/tests/batch/${batch.batchId}/status`)"
            />
          </div>
        </div>
      </UCard>

      <!-- Sessions -->
      <UCard class="shadow-sm">
        <template #header>
          <h2 class="text-base font-semibold">
            Recent Sessions
          </h2>
        </template>
        
        <p
          v-if="sessions.length === 0"
          class="text-center text-sm text-gray-500 py-4"
        >
          No sessions
        </p>
        <div
          v-else
          class="divide-y divide-gray-200 dark:divide-gray-800"
        >
          <div 
            v-for="session in sessions.slice(0, 8)" 
            :key="session.sessionId"
            class="flex justify-between items-center py-3 first:pt-0 last:pb-0 gap-4"
          >
            <div class="min-w-0 flex-1">
              <h3
                class="font-semibold text-sm truncate text-gray-700 dark:text-gray-200"
                :title="session.ticket?.testType || session.agentName"
              >
                {{ session.ticket?.testType || session.agentName }}
              </h3>
              <div class="flex items-center gap-2 mt-1">
                <span class="font-mono text-xs text-gray-400">{{ session.sessionId }}</span>
                <UBadge
                  :color="mapColor(session.status)"
                  variant="subtle"
                  size="sm"
                >
                  {{ getCleanStatus(session.status) }}
                </UBadge>
              </div>
            </div>
            <UButton 
              label="Inspect" 
              variant="link" 
              size="sm" 
              class="p-0 font-semibold"
              @click="router.push(`/tests/session/${session.sessionId}/status`)"
            />
          </div>
        </div>
      </UCard>
    </div>
  </div>
</template>

// src/main/webui/src/components/RecentActivity.svelte
<script>
  import Loader2 from '@lucide/svelte/icons/loader-2';
  import { navigate } from '@/router.js';
  import { useBatchesQuery, useSessionsQuery } from '@/composables/queries';
  import { getCleanStatus, getStatusColor } from '@/utils/format';

  const batchesQuery = useBatchesQuery();
  const sessionsQuery = useSessionsQuery();

  let isLoading = $derived($batchesQuery.isPending || $sessionsQuery.isPending);
  let hasError = $derived($batchesQuery.error || $sessionsQuery.error);
  let errorMessage = $derived(() => {
    const err = $batchesQuery.error || $sessionsQuery.error;
    return err ? (err.message || String(err)) : '';
  });

  let batches = $derived($batchesQuery.data || []);
  let sessions = $derived($sessionsQuery.data || []);

  const getBadgePreset = (status) => {
    const col = getStatusColor(status);
    if (col === 'danger') return 'preset-filled-error-500';
    if (col === 'secondary') return 'preset-tonal-surface-500';
    if (col === 'success') return 'preset-filled-success-500';
    if (col === 'info') return 'preset-filled-primary-500';
    if (col === 'warning') return 'preset-filled-warning-500';
    return 'preset-tonal-surface-500';
  };
</script>

<div>
  {#if isLoading}
    <div class="flex justify-center py-6">
      <Loader2 class="animate-spin w-8 h-8 text-primary-500" />
    </div>
  {:else if hasError}
    <div class="alert preset-tonal-error p-4 rounded-lg">
      <span class="font-medium">Error loading recent activity:</span> {errorMessage()}
    </div>
  {:else}
    <div class="grid grid-cols-1 lg:grid-cols-2 gap-6">
      <!-- Batches -->
      <div class="card p-6 bg-surface-100 dark:bg-surface-900 border border-surface-200 dark:border-surface-800 rounded-lg shadow-sm">
        <h2 class="text-lg font-semibold text-surface-900 dark:text-white mb-4">Recent Batches</h2>
        
        {#if batches.length === 0}
          <p class="text-center text-sm text-surface-500 py-4">No batches</p>
        {:else}
          <div class="divide-y divide-surface-200 dark:divide-surface-800">
            {#each batches.slice(0, 8) as batch (batch.batchId)}
              <div class="flex justify-between items-center py-3 first:pt-0 last:pb-0 gap-4">
                <div class="min-w-0 flex-1">
                  <h3 class="font-semibold text-sm truncate text-surface-800 dark:text-surface-200" title={batch.testName}>
                    {batch.testName}
                  </h3>
                  <div class="flex items-center gap-2 mt-1">
                    <span class="font-mono text-xs text-surface-400">{batch.batchId}</span>
                    <span class="badge {getBadgePreset(batch.status)} text-[10px] px-1.5 py-0.5">
                      {getCleanStatus(batch.status)}
                    </span>
                  </div>
                </div>
                <button 
                  class="btn btn-sm preset-tonal-surface-500"
                  onclick={() => navigate(`/tests/batch/${batch.batchId}/status`)}
                >
                  Monitor
                </button>
              </div>
            {/each}
          </div>
        {/if}
      </div>

      <!-- Sessions -->
      <div class="card p-6 bg-surface-100 dark:bg-surface-900 border border-surface-200 dark:border-surface-800 rounded-lg shadow-sm">
        <h2 class="text-lg font-semibold text-surface-900 dark:text-white mb-4">Recent Sessions</h2>
        
        {#if sessions.length === 0}
          <p class="text-center text-sm text-surface-500 py-4">No sessions</p>
        {:else}
          <div class="divide-y divide-surface-200 dark:divide-surface-800">
            {#each sessions.slice(0, 8) as session (session.sessionId)}
              <div class="flex justify-between items-center py-3 first:pt-0 last:pb-0 gap-4">
                <div class="min-w-0 flex-1">
                  <h3 class="font-semibold text-sm truncate text-surface-800 dark:text-gray-200" title={session.ticket?.testType || session.agentName}>
                    {session.ticket?.testType || session.agentName}
                  </h3>
                  <div class="flex items-center gap-2 mt-1">
                    <span class="font-mono text-xs text-surface-400">{session.sessionId}</span>
                    <span class="badge {getBadgePreset(session.status)} text-[10px] px-1.5 py-0.5">
                      {getCleanStatus(session.status)}
                    </span>
                  </div>
                </div>
                <button 
                  class="btn btn-sm preset-tonal-surface-500"
                  onclick={() => navigate(`/tests/session/${session.sessionId}/status`)}
                >
                  Inspect
                </button>
              </div>
            {/each}
          </div>
        {/if}
      </div>
    </div>
  {/if}
</div>
